codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project: yes
    patch: no
    changes: no

comment:
  layout: "header, diff, changes, sunburst, suggestions, tree"
  branches: null
  behavior: default

