language: swift
os: osx
osx_image: xcode9.1
xcode_sdk: iphonesimulator10.0
xcode_project: Binson.xcodeproj
xcode_scheme: BinsonTests

script:
  - make all

env:
  - SWIFT_VERSION=4.0

notifications:
  email:
    recipients:
      - kenneth@pernyer.se
    on_success: never
    on_failure: always
