os: osx
osx_image: xcode9.1

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
  - make all

env:
  - SWIFT_VERSION=4.0
  - SWIFT_VERSION=4.1

notifications:
  email:
    recipients:
      - kenneth@pernyer.se
    on_success: never
    on_failure: always
