language: swift
os: osx
osx_image: xcode9.4
xcode_project: Binson.xcodeproj
xcode_scheme: BinsonTests

script:
  - swiftlint
  - xcodebuild -version
  - xcodebuild -project Binson.xcodeproj -scheme Binson-Package -sdk macosx -configuration Debug -enableCodeCoverage YES test | xcpretty
  - bash <(curl -s https://codecov.io/bash) -J Binson -cF osx
  - xcodebuild -project Binson.xcodeproj -scheme Binson-Package -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" -configuration Debug ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test | xcpretty
  - bash <(curl -s https://codecov.io/bash) -J Binson -cF ios

env:
  - SWIFT_VERSION=4.1

notifications:
  email:
    recipients:
      - kenneth@pernyer.se
      - dreadrik@gmail.com
    on_success: never
    on_failure: always
