language: swift
os: osx
osx_image: xcode9.1
xcode_project: Binson.xcodeproj
xcode_scheme: BinsonTests

script:
  - make all

env:
  - SWIFT_VERSION=4.0

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Binson'

notifications:
  email:
    recipients:
      - kenneth@pernyer.se
    on_success: never
    on_failure: always
